project_identifier: yarn
api_key_env: CROWDIN_API_KEY
base_path: .

files:
  - source: '/en/**/*'
    translation: '/%locale%/**/%original_file_name%'
    languages_mapping:
      locale:
        af: af
        ar: ar
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        en: en
        es-ES: es-ES
        fa-IR: fa-IR
        fi: fi
        fr: fr
        he: he
        hu: hu
        id-ID: id-ID
        it: it
        ja: ja
        ko: ko
        mr-IN: mr-IN
        nl: nl
        no-NO: no-NO
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt-PT
        ro: ro
        ru: ru
        sk-SK: sk-SK
        sr: sr
        sv-SE: sv-SE
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh-Hans
        zh-TW: zh-Hant
  - source: '/_data/i18n/en.yml'
    translation: '/_data/i18n/%locale%.yml'
    languages_mapping:
      locale:
        af: af
        ar: ar
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        en: en
        es-ES: es-ES
        fa-IR: fa-IR
        fi: fi
        fr: fr
        he: he
        hu: hu
        id-ID: id-ID
        it: it
        ja: ja
        ko: ko
        mr-IN: mr-IN
        nl: nl
        no-NO: no-NO
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt-PT
        ro: ro
        ru: ru
        sk-SK: sk-SK
        sr: sr
        sv-SE: sv-SE
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh-Hans
        zh-TW: zh-Hant
